# Generated by Django 5.2.10 on 2026-02-04 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(choices=[('electricity', 'Electricity'), ('recharge', 'Recharge'), ('pan', 'PAN'), ('train', 'Train'), ('bus', 'Bus'), ('flight', 'Flight'), ('car', 'Car'), ('bike', 'Bike'), ('health', 'Health'), ('crop', 'Crop'), ('topup', 'Topup'), ('esevai', 'Esevai'), ('other_work', 'Other')], max_length=20)),
                ('customer_name', models.CharField(max_length=20)),
                ('account_no', models.CharField(max_length=25)),
                ('mobile', models.CharField(max_length=10, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('topup', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('iscsc', models.BooleanField(default=1)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Ledger',
            },
        ),
    ]
